MSVC support
Coding-Bunker/unofficial-discord-client pull request #38
Opened 2021-06-04 18:54 UTC by clin1234

2021-06-04 19:08 UTC, guerinoni requested changes
Very good! Thank you! I want only suggest to change the position of `&` in order to be compliant with .clang-format

2021-06-04 21:14 UTC, guerinoni commented
Rebase it, don't "reverse merge"

2021-06-05 21:26 UTC, clin1234 reviewed
Sure

2021-06-06 13:52 UTC, guerinoni requested changes

2021-06-06 13:52 UTC, guerinoni commented on src/app/main.cpp
> +    // QGuiApplication;
This?

2021-06-06 13:53 UTC, guerinoni commented
Rebase correctly in order to remove `e4d85732379fc6b5efead54879f20cc76ab4607e`

2021-06-06 14:11 UTC, closed without merging