Add handling for components, attachments, embeds, and emoji (only preliminary).
Coding-Bunker/unofficial-discord-client pull request #53
Opened 2021-06-22 18:30 UTC by clin1234

2021-06-26 16:06 UTC, clin1234 commented
Status?

2021-06-26 16:21 UTC, guerinoni commented
I can't merge it... 
- 0bf8eeb merge instead of rebase
- Omit version number, add features for channel and message objects duplicated commit
- Add preliminary support for attachments and roles duplicated commit
- Add preliminary support for attachments and roles duplicated commit
- Replace .value call with subscript operator for settings duplicated commit
- Remove Git diff crud left by a previous commit duplicated commit
- Fix formatting issue introduced by Qt Creator duplicated commit
- Run clang-format duplicated commit
- Fix up bungles of previous commits duplicated commit
- Add preliminary support for attachments and roles duplicated commit
- Add preliminary support for attachments and roles duplicated commit
- Fix build errors, and rename role files to proper case duplicated commit
- Clean code duplicated commit
- Add latest version of API duplicated commit

2021-06-27 20:53 UTC, clin1234 commented
Should be fixed...

2021-06-28 19:14 UTC, guerinoni requested changes
Also is not correctly rebase because it complains about many conflict :^)

2021-06-28 19:14 UTC, guerinoni commented on src/core/Guild.cpp
> +<<<<<<< HEAD
Build fails with this

2021-06-28 19:14 UTC, guerinoni commented on src/core/Channel.cpp
> +
Remove unused code

2021-06-28 19:14 UTC, guerinoni commented on src/core/Component.cpp
> +        // m_emoji.emplace(t);
Unused! Add a TODO or FIXME instead and a warning print

2021-06-28 19:14 UTC, guerinoni commented on src/core/Component.cpp
> +*/
Remove unused

2021-06-28 19:14 UTC, guerinoni commented on src/core/Component.cpp
> +        // m_component.emplace<Button>(but);
Unused! Add a TODO or FIXME instead and a warning print

2021-06-28 19:14 UTC, guerinoni commented on src/core/Component.cpp
> +constexpr int Component::type()
Maybe is better an enum, but at least add a FIXME

2021-06-28 19:14 UTC, guerinoni commented on src/core/Emoji.cpp
> +}*/
Unused!

2021-06-28 19:14 UTC, guerinoni commented on src/core/Emoji.cpp
> +        // m_user.emplace(u);
Unused! Add a TODO or FIXME instead and a warning print

2021-06-28 19:14 UTC, guerinoni commented on src/core/Emoji.hpp
> +//#include "User.hpp"
Unused

2021-06-28 19:14 UTC, guerinoni commented on src/core/Emoji.hpp
> +    // Emoji();
Unused

2021-06-28 19:14 UTC, guerinoni commented on src/qml/main.qml
> +//import "Menubar" as Private
?

2021-07-01 15:26 UTC, closed without merging